version: "3.9"
services:
  backend:
    build:
      context: ./backend-v2
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
    depends_on:
      - database

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4200:80"

  database:
    image: postgres:14
    container_name: postgres_db
    environment:
      POSTGRES_USER: pgadmin
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: db-proj
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
