networks:
  container-network:
    driver: bridge

services:
  postgres:
    image: postgres:latest
    container_name: container-postgres
    environment:
      POSTGRES_PASSWORD: 123
    ports:
      - "5433:5432"
    networks:
      - container-network
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    container_name: container-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: gusttavo.barbosa.br@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 123
    ports:
      - "5434:80"
    networks:
      - container-network
    restart: always
