services:
  db:
    image: postgres:latest
    container_name: container-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: dataBaseProject
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    container_name: container-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: gusttavo.barbosa.br@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 123
    ports:
      - "5434:80"
    restart: always
    depends_on:
      - db

volumes:
  postgres-data:
    driver: local
