networks:
  container-network:
    driver: bridge

services:
  postgres:
    image: postgres:latest
    container_name: container-postgres
    environment:
      POSTGRES_PASSWORD: 123
    ports:
      - "5433:5432"
    networks:
      - container-network
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    container_name: container-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: gusttavo.barbosa.br@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 123
    ports:
      - "5434:80"
    networks:
      - container-network
    restart: always

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: container-api
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL:  jdbc:postgresql://postgres:5432/DbProjectTest
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123
    depends_on:
      - postgres
    networks:
      - container-network
    restart: always